/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CltControl' at '29/12/15 11:10' with Gradle 2.9
 *
 * @author CltControl, @date 29/12/15 11:10
 */
public class ICalculator {
    public boolean someLibraryMethod() {
        return true;
    }
}
